name: Initialize swarm on manager
hosts: manager
become: yes
tasks:
- name: Initialize docker swarm
shell: |
docker swarm init --advertise-addr {{ ansible_host }}
register: swarm_init
failed_when: false


- name: Get worker join-token
shell: docker swarm join-token worker -q
register: worker_token


- name: Set join token fact for controller
set_fact:
join_token: "{{ worker_token.stdout }}"


- name: Join workers to swarm
hosts: workers
become: yes
tasks:
- name: Join the swarm (if not manager)
shell: |
docker swarm join --token {{ hostvars[groups['manager'][0]].join_token }} {{ hostvars[groups['manager'][0]].ansible_host }}:2377
register: join_out
failed_when: false


- name: Wait for nodes to be ready
hosts: manager
tasks:
- name: List nodes
shell: docker node ls
register: node_list


- debug:
var: node_list.stdout